---

- hosts: servers
  tasks:
    # - name: Change the hostname to our standard
    #   become: yes
    #   hostname:
    #     # name="{{ inventory_hostname }}"
    #     name="{{ new_hostname }}" 
    #   when:
    #     ansible_fqdn != ansible_ssh_host

    # - name: restart machine
    #   become: yes
    #   command: shutdown -r now "Ansible updates triggered"
    #   async: 0
    #   poll: 0
    #   ignore_errors: True
    #   when:
    #     reboot is defined

    # - name: Waiting for server to come back up
    #   local_action: wait_for host="{{ inventory_hostname }}" port=22 state=started

    # - name: Fix /etc/hosts removing the old hostname
    #   become: yes
    #   tags:
    #     - hosts
    #   lineinfile:
    #     state=present
    #     dest=/etc/hosts
    #     line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
    #     regexp="^{{ ansible_default_ipv4.address }}"
    #   when:
    #     ansible_fqdn != inventory_hostname

    # - name: Validate ansible_fqdn == inventory_hostname
    #   tags:
    #     - validate
    #   assert:
    #     that:
    #       ansible_fqdn == inventory_hostname
    - name: Set a hostname
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"
      become: true

    - name: Enable SystemdCgroup
      lineinfile:
        dest: /etc/hosts
        search_string: "127.0.1.1"
        line: "127.0.1.1 {{ new_hostname }}"
        state: present
      become: true

    - name: Unconditionally reboot the machine with all defaults
      reboot:
      become: true