---
- hosts: servers
  become: true
  vars_prompt:
  - name: username
    prompt: "Enter Username"
  - name: new_password
    prompt: "Enter new password"
  tasks:
  - name: Add a new user
    user:
      name: "{{ username }}"
      shell: /bin/bash
      password: "{{ new_password|password_hash('sha512') }}"
  - name: Add new user to the sudoers
    copy:
      dest: "/etc/sudoers.d/{{ username }}"
      content: "{{ username }}  ALL=(ALL:ALL)  NOPASSWD: ALL"